### ISSUE TITLE
dcm_parse fails on v5.0+

### ISSUE THREAD

**Issue by BenRussert** [JuliaIO/DICOM.jl#13]
I messed around with this package a little over the weekend and ran into some problems. I wonder if this can be easily fixed, but i'm new to DICOM in general so i'm afraid to get too deep without input from the community. I'd love to help, but thought i'd get some discussion started first.

Below are some results I got using one of the test files linked in runtests.jl ( filename: "MGIMAGEI" ):

If I Pkg.checkout("DICOM") I can get dcm_parse to work on julia 4.7. If I don't use the dev branch the package wont load (same for v5.0).

On v5.0 the function fails, I think due to some of the changes in array indexing and type conversion. 
Below is the warning I get:

```
MethodError: no method matching Array{T,N}(::Type{UInt8}, ::Array{UInt16,1}, ::Array{UInt16,1}, ::Int64)
Closest candidates are:
  Array{T,N}{T}(::Type{T}, ::Int64, ::Int64, ::Int64) at boot.jl:332
  Array{T,N}{T}(::Type{T}, ::Int64...) at boot.jl:329
  Array{T,N}{T}(::Type{T}, ::Integer, ::Integer, ::Integer) at sysimg.jl:91
  ...

 in pixeldata_parse(::IOStream, ::UInt32, ::String, ::Array{Any,1}) at /home/juser/.julia/v0.5/DICOM/src/DICOM.jl:176
 in element(::IOStream, ::Bool, ::Array{Any,1}) at /home/juser/.julia/v0.5/DICOM/src/DICOM.jl:285
 in dcm_parse(::IOStream) at /home/juser/.julia/v0.5/DICOM/src/DICOM.jl:395
```

**Comment by ultradian** [comment]
I just submitted a PR to fix this.  It is my first PR and I'm still learning DICOM, so any comments are appreciated.  I only worked on `dcm_parse`, and didn't touch `dcm_write()`

**Comment by BenRussert** [comment]
Nice PR! I figured this repo was dead until this fix.

I sent you a PR to fix one line since bytestring() is now deprecated.

**Comment by BenRussert** [comment]
#14 resolves this issue
