### ISSUE TITLE
version 0.0.2 is not on metadata

### ISSUE THREAD

**Issue by haflo1** [JuliaIO/DICOM.jl#25]
Pkg.add("DICOM") still installs version  0.0.1
Pkg.update("DICOM") doesn't update version too

**Comment by notZaki** [comment]
You might already know this, but while the metadata issue gets sorted out, the current master can be installed by `Pkg.checkout("DICOM")`

**Comment by ihnorton** [comment]
@notZaki you have commit access now if you want to look at this. If not I'll try to take a look this weekend (and review your PRs too).

**Comment by ihnorton** [comment]
@notZaki I see https://github.com/JuliaIO/DICOM.jl/releases/tag/v0.1.0 just changed, which probably shouldn't happen because it was already in METADATA (but should be ok as long as the hash stays the same).

**Comment by notZaki** [comment]
I think the metadata version was v0.0.1, not v0.1.0.
I had to use a new minor release number because there was no previous `REQUIRE`

**Comment by ihnorton** [comment]
Whoops, right. It's still there at the bottom on the release page. Carry on 👍

**Comment by notZaki** [comment]
There was a hold up at metadata.jl which was preventing package updates. 
It was resolved today, so hopefully the metadata will be updated with the recent master soon.

**Comment by notZaki** [comment]
The recent master (v0.1.0) is now on metadata, and should be available after `Pkg.update()`.

I guess this also resolves #12.
