### ISSUE TITLE
typo ?

### ISSUE THREAD

**Issue by vsaase** [JuliaIO/DICOM.jl#42]
Hi, should this be read_element instead of element?
https://github.com/JuliaIO/DICOM.jl/blob/35547d73ed940541bbb821902f66f8e4563d1511/src/DICOM.jl#L465

**Comment by vsaase** [comment]
because the function `element` is not defined anymore

**Comment by notZaki** [comment]
Yup, that's a typo. Thanks for pointing it out.

I think that part of the code is only used for encapsulated/compressed images which aren't well-supported anyways. 

I tried to change it to `read_element` (with updated function arguments) but that still raised an error. I'll give it another shot in the next two weeks, but a PR is welcome if someone else wants to take a stab at it.

**Comment by notZaki** [comment]
Thanks for making the changes in #45. 
The latest version (0.6.2) has your fixes.
